remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: About Me
description: ML Data Engineer | Analytical Researcher | Problem Solver | Mentor

github:
  zip_url: http://example.com/download.zip
  another_url: another value
  
  
